### ISSUE TITLE
Convenience functions are more useful if return non-nil

### ISSUE THREAD

**Issue by 0x3444ac53** [zc1036/lips#1] opened 2023-10-16 15:33 UTC

**Comment by zc1036** [comment] 2023-10-22 19:44
Which functions were you thinking? The reason they return NIL right now is because if they return anything else, that thing will be printed, which we don't want, because they're just used for their side effects rather than their return value.

**Comment by 0x3444ac53** [comment] 2023-10-24 01:52
```
\(macro atag (link class text)
    (% "<a href=\"~a\" class=\"~a\">~a</a>" link class text))

\(macro page (link text)
    ($atag link "pages" text)) 

\(macro art (link text)
    ($atag link "article" text)) 

\(macro artist (link text)
    ($atag link "bloglink" text))

\(defn ulist (test)
    ($ "<ul>")
    (loop for i in test do 
        (% "<li>~a</li>" i))
    ($ "</ul>"))

\(macro icon (iconname) (% "<i style=color:inherit class='fa-solid ~a'></i>" iconname))
```

Here is an example from where I'm using this project to template my website. I want to be able to do something like this 

```
<!------
\(defv articles nil) 
\(push (art "link" "title") articles)
\(push (art "link" "title") articles)
\(push (art "link" "title") articles)
\(push (art "link" "title") articles)
--------> 
\(ulist art) 
```

Apologies for the likely syntax error, as I don't actually know lisp. 

Which in my [(very bad) templating language](https://GitHub.com/0x3444ac53/HCSL) works fine, but doesn't work easily in lips. 

Also, I only created the issue because I wasn't expecting a response and was planning to just fork the project. But as long as I have your attention I found your project after I made my language and someone on hscknews pointed me to this. I think it's really cool! Thanks for making this!

**Comment by zc1036** [comment] 2023-10-24 18:39
I think I see what you mean. I think the issue is that you're using the % operator, which is used for side effects, when you just want string formatting. You can use the FORMAT function for that. Using your example:

```lisp
\(defn atag (link class text)
    ;; using NIL for the second argument here causes FORMAT to return
    ;; the string rather than printing it to a stream
    (format nil "<a href=\"~a\" class=\"~a\">~a</a>" link class text))

\(macro page (link text)
    (atag link "pages" text))

\(macro art (link text)
    (atag link "article" text))

\(macro artist (link text)
    (atag link "bloglink" text))

\(defn ulist (test)
    ($ "<ul>")
    (loop for i in test do
        (% "<li>~a</li>" i))
    ($ "</ul>"))

\(macro icon (iconname) (% "<i style=color:inherit class='fa-solid ~a'></i>" iconname))

\(defv articles nil)
\-(push ($art "link" "title") articles)
\-(push ($art "link" "title") articles)
\-(push ($art "link" "title") articles)
\-(push ($art "link" "title") articles)

\(ulist articles)
```
That will result in the output
```
<ul><li><a href="link" class="article">title</a></li><li><a href="link" class="article">title</a></li><li><a href="link" class="article">title</a></li><li><a href="link" class="article">title</a></li></ul>%
```
I also added the `\-` feature, which suppresses printing out the result of the form evaluation, so that you don't have to have HTML comments like you were. You'll find it in master.

**Comment by 0x3444ac53** [comment] 2023-10-25 02:13
Thank you so much! I'll close this issue once I have a chance to test it out 😁

**Comment by zc1036** [comment] 2023-11-01 20:55
@0x3444ac53 did you get a chance to test this out?

**Comment by zc1036** [comment] 2023-11-09 17:31
Closing, assuming this is fixed. Open another issue if you're still having trouble.

**Closed as completed by zc1036** 2023-11-09 17:31 UTC
